### PR TITLE
Update workspace navigation UX

### PR DESCRIPTION
**Pull request by Regaddi**
# Short summary of changes (please include issue #)

This PR updates the workspace navigation to be a bit more streamlined and intuitive to use.

- Clicking a workspace sidebar item opens the workspace edit form
- Added a menu to workspace sidebar items (similar to conversations), with options to "Go to Workspace" and "Delete…"
- Added a big "Go to Workspace" button at the top of the workspace edit form
- Removed "Workspaces" from conversation sidebar
- Updated Workspace switcher (in conversation sidebar)

**Screenshots**

CleanShot 2024-10-23 at 10 15 25@2x
CleanShot 2024-10-23 at 10 15 47@2x
CleanShot 2024-10-23 at 10 16 12@2x
CleanShot 2024-10-23 at 10 16 46@2x
CleanShot 2024-10-23 at 10 17 00@2x

### CODE REVIEW

**Comment by markbackman** [comment]
UX wise, this is better 😌. Thank you.

**Comment by markbackman** [comment]
On this branch (haven't tested main), when I create a new "Informational" workspace, a "conversational" workspace is created instead. I think this is a bug.

Also, in ConfigurationForm.tsx, `text_filter` should be:
```
{
  name: "text_filter",
  value: {
    filter_code:
      formState.voiceSettings.interactionMode === "informational",
    filter_tables:
      formState.voiceSettings.interactionMode === "informational",
  },
},
```

Informational should use BotLLMText, which prints out the Bot response in its entirety (not word for word). And, the TTS should skip speaking code and tables. This configure should do that, if I understand correctly.

**Comment by Regaddi** [comment]
> On this branch (haven't tested main), when I create a new "Informational" workspace, a "conversational" workspace is created instead. I think this is a bug.

Hmm, I can't confirm this behavior. It's working correctly for me 🤔 
Could you share a screencast showcasing the issue you're seeing?

> Also, in ConfigurationForm.tsx, `text_filter` should be:
> 
> ```
> {
>   name: "text_filter",
>   value: {
>     filter_code:
>       formState.voiceSettings.interactionMode === "informational",
>     filter_tables:
>       formState.voiceSettings.interactionMode === "informational",
>   },
> },
> ```
> 
> Informational should use BotLLMText, which prints out the Bot response in its entirety (not word for word). And, the TTS should skip speaking code and tables. This configure should do that, if I understand correctly.

We only want to filter code and tables when the interaction mode is "conversational". In "informational" mode everything should be printed. Unless I'm completely missing the point I think the current logic works as intended.

**Comment by markbackman** [comment]
> We only want to filter code and tables when the interaction mode is "conversational". In "informational" mode everything should be printed. Unless I'm completely missing the point I think the current logic works as intended.

That's not quite right. The text_filter is applied to the words that the TTS speaks.

- In conversational mode, we always want the bot to say everything (expect for markdown chars). The BotTtsText reflects the words spoken by the bot. So, if you apply the text_filter for code and tables, then the bot will never output the code or tables.
- In informational mode, you should be using BotLlmText, which is the LLM output from the bot. That means you can augment the speech of the bot (i.e. applying code and table filters) while still seeing the entire text output from the bot.

Make sense?

**Comment by markbackman** [comment]
I can't repro that workspace type issue. I'll keep an eye out for it.

**Comment by Regaddi** [comment]
> That's not quite right. The text_filter is applied to the words that the TTS speaks.

I feel like this should be a separate configuration from interaction mode. It feels weird that the AI speaks code & tables in conversational, but doesn't in informational mode. Shouldn't this be separate elements in the workspace's TTS config?

**Comment by markbackman** [comment]
> > That's not quite right. The text_filter is applied to the words that the TTS speaks.
> 
> I feel like this should be a separate configuration from interaction mode. It feels weird that the AI speaks code & tables in conversational, but doesn't in informational mode. Shouldn't this be separate elements in the workspace's TTS config?

Possibly. But, in conversation mode, the bot _has_ to speak all of the words or else text will be missing from the response. The issue with that is some TTS services will break if they have to read code and tables. We want to avoid that where possible.

The idea with information mode is that it's a preset that helps you quickly see all of the text output, right away. And, you only hear the bot speak the meaningful parts. (Speaking code or tables is prone to annoying the user and make the TTS fail, so we should remove it).

Having spent a bunch of time working on this, I have a strong inclination that what I'm suggesting is a good UX.

**Comment by markbackman** [comment]
Quick demo of what I'm talking about: https://share.cleanshot.com/8KjyfNnT.

**Comment by Regaddi** [comment]
I suggest we move the text_filter / interaction mode changes to a separate PR.

**Pull request merged**
